### ISSUE TITLE
Sky Italy Logos

### ISSUE THREAD

**Issue by gioluca2** [zag2me/TheLogoDB#1]
Hi, by 2nd of July there are new logos for Sky Italy. Can you update all? Can you add also DAZN logos?
Thanks

**Comment by zag2me** [comment]
Sure I will need sources though:

Will they look the same as the UK ones in the future? Like this?

![sky-sport-seriea-k](https://user-images.githubusercontent.com/1050512/44396221-21473f80-a534-11e8-8607-9532de03c32c.png)
![8714_home](https://user-images.githubusercontent.com/1050512/44396442-c95d0880-a534-11e8-95ea-c5182b80b75d.png)
![7507_home](https://user-images.githubusercontent.com/1050512/44396443-c95d0880-a534-11e8-87cc-885f8e0c7b09.png)

This is about the best quality I can find so far, without someone redrawing it.

EDIT1: Here is a good quality UK version with "sports" not "sport"
![sky_sports_logo_2017](https://user-images.githubusercontent.com/1050512/44396937-5ce30900-a536-11e8-8614-61c11c03f195.png)


EDIT2: May be a useful SVG here
https://upload.wikimedia.org/wikipedia/commons/0/09/Sky_Sports_logo_2017.svg

**Comment by gioluca2** [comment]
Thanks. What about DAZN?
